spring:
   application.name: microservice-hystrix-turbine
server:
   port: 8031
security.basic.enabled: false
turbine:
   aggregator:
      clusterConfig: default # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
   appConfig: microservice-api-gateway, microservice-consumer-movie-ribbon-with-hystrix, microservice-consumer-movie-feign-with-hystrix-stream ### 配置Eureka中的serviceId列表，表明监控哪些服务
   clusterNameExpression: new String("default")
   combine-host: true
# 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
# 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
# 3. 当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC
   instanceUrlSuffix:
      default: actuator/hystrix.stream
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
management:
   endpoints:
      web:
         exposure:
            include: '*'
         cors:
            allowed-origins: '*'
            allowed-methods: '*'
            
# 参考：http://blog.csdn.net/liaokailin/article/details/51344281
# 参考：http://blog.csdn.net/zhuchuangang/article/details/51289593